apiVersion: v1
kind: Pod
metadata:
  name: example
  namespace: with-global-limit2 
spec: 
  automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
  containers: 
    - name: memory-limit 
      image: nginx:1.2.3
      resources: 
        limits:
          memory: 1G
          cpu: 600m
        request:
          memory: 512Mi
          cpu: 200m

